// Generates the Optima Express edge function and head function for Netlify (ORBI-82, Phase 3).
//
// Written through Netlify's Frameworks API: files in <root>/.netlify/v1/{edge-functions,functions}/
// deploy with the site and route by their inline `config`, so a site needs no netlify.toml entry
// (verified on a real deploy in the Phase 3 spike). Opt-in per site — `optimaExpress.edge` in the
// theme options — because it's Netlify-specific and needs the plugin's edge secret configured.
//
// The runtime code lives in src/edge/*.mjs as ordinary modules (so it can be exercised locally).
// The generated files are those modules concatenated: shared helpers, an inline CONFIG, the
// handler, and a literal `config` export (Netlify reads it statically).

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { isIndexable, type OptimaExpressSettings, type OptimaExpressRoute } from './optimaExpress.js';

export interface OptimaExpressEdgeOptions {
  /**
   * The ORBI-82 experiment: listing URLs with an odd listing number get the client head writer
   * only (group A), even ones the edge head (group B). Off: every URL is B.
   */
  split?: boolean;
  /**
   * Optional "is this listing displayable?" check, as a URL template. `{listingNumber}`,
   * `{boardId}` (any route param) and `{activationToken}` are filled in; header values take the
   * same placeholders. 404 → the page is served as a real 404; 200 or anything else → carry on.
   * Status only — the body is never read.
   */
  displayability?: { url: string; headers?: Record<string, string> };
  /** How long the edge waits for the head function before serving the plain shell. Default 8000. */
  headTimeoutMs?: number;
}

const EDGE_FILE = 'soames-ihf.js';
const HEAD_FILE = 'soames-ihf-head.mjs';
const SITEMAP_FILE = 'soames-ihf-sitemap.mjs';
const HEAD_PATH = '/_soames/ihf-head';

/** `/a/:x/:y` → anchored regex source with one group per param, trailing slash optional. */
function toPattern(r: OptimaExpressRoute): { pattern: string; keys: string[] } {
  const keys: string[] = [];
  const body = r.path.replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replace(/:([A-Za-z][A-Za-z0-9_]*)/g, (_, k: string) => {
    keys.push(k);
    return '([^/]+)';
  });
  return { pattern: `^${body}/?$`, keys };
}

async function source(name: string): Promise<string> {
  return fs.readFile(fileURLToPath(new URL(`../edge/${name}`, import.meta.url)), 'utf8');
}

/** A module's body with its imports removed (and, for the shared helpers, its exports). */
function inline(src: string, stripExports: boolean): string {
  let out = src.replace(/^import\s[\s\S]*?from\s+['"][^'"]+['"];\s*$/gm, '');
  if (stripExports) out = out.replace(/^export (const|function|async function) /gm, '$1 ');
  return out;
}

export async function removeEdge(root: string): Promise<void> {
  await fs.rm(path.join(root, '.netlify', 'v1', 'edge-functions', EDGE_FILE), { force: true });
  await fs.rm(path.join(root, '.netlify', 'v1', 'functions', HEAD_FILE), { force: true });
  await fs.rm(path.join(root, '.netlify', 'v1', 'functions', SITEMAP_FILE), { force: true });
}

/** The listing sitemap paths a site serves: one per experiment group, or one in all. */
export function sitemapFiles(opts: OptimaExpressEdgeOptions): Record<string, 'A' | 'B' | 'all'> {
  return opts.split ? { '/sitemap-idx-a.xml': 'A', '/sitemap-idx-b.xml': 'B' } : { '/sitemap-idx.xml': 'all' };
}

export async function writeEdge(
  root: string,
  oe: OptimaExpressSettings,
  opts: OptimaExpressEdgeOptions,
  site: { siteUrl: string; wpBase: string },
  logger: { info(m: string): void; warn(m: string): void },
): Promise<string[]> {
  const routes = oe.routes.filter((r) => isIndexable(r.type)).map((r) => ({ type: r.type, path: r.path, ...toPattern(r) }));
  if (!site.siteUrl) {
    logger.warn('Optima Express edge: no `siteUrl` option, so canonicals will name whichever host served the request.');
  }
  const common = inline(await source('ihfCommon.mjs'), true);
  const header = `// GENERATED by soames-astro-theme (src/lib/ihfEdge.ts) — do not edit.\n`;

  const edgeConfig = {
    siteUrl: site.siteUrl,
    routes,
    split: !!opts.split,
    displayability: opts.displayability ?? null,
    activationToken: oe.kestrel.activationToken,
    headPath: HEAD_PATH,
    headTimeoutMs: opts.headTimeoutMs ?? 8000,
    checkTimeoutMs: 2000,
  };
  const edge =
    header +
    `const CONFIG = ${JSON.stringify(edgeConfig)};\n` +
    common +
    inline(await source('ihfEdge.mjs'), false) +
    // onError: bypass — if the function itself throws, Netlify serves the request as if it
    // weren't there (the plain shell), which is the fail-open this design depends on.
    `\nexport const config = ${JSON.stringify({ pattern: routes.map((r) => r.pattern), onError: 'bypass' })};\n`;

  const headConfig = { routes, wpBase: site.wpBase.replace(/\/+$/, ''), headPath: HEAD_PATH, wpTimeoutMs: 9000 };
  const head =
    header +
    `const CONFIG = ${JSON.stringify(headConfig)};\n` +
    common +
    inline(await source('ihfHead.mjs'), false) +
    `\nexport const config = ${JSON.stringify({ path: `${HEAD_PATH}/*` })};\n`;

  // Listing sitemaps (Phase 4): needs Soames plugin 1.6.0+; served at request time, cached.
  const files = sitemapFiles(opts);
  const sitemapConfig = { routes, wpBase: headConfig.wpBase, siteUrl: site.siteUrl, split: !!opts.split, files, wpTimeoutMs: 20000 };
  const sitemap =
    header +
    `const CONFIG = ${JSON.stringify(sitemapConfig)};\n` +
    common +
    inline(await source('ihfSitemap.mjs'), false) +
    `\nexport const config = ${JSON.stringify({ path: Object.keys(files) })};\n`;

  const edgeDir = path.join(root, '.netlify', 'v1', 'edge-functions');
  const fnDir = path.join(root, '.netlify', 'v1', 'functions');
  await fs.mkdir(edgeDir, { recursive: true });
  await fs.mkdir(fnDir, { recursive: true });
  await fs.writeFile(path.join(edgeDir, EDGE_FILE), edge);
  await fs.writeFile(path.join(fnDir, HEAD_FILE), head);
  await fs.writeFile(path.join(fnDir, SITEMAP_FILE), sitemap);
  logger.info(
    `Optima Express edge: ${routes.length} indexable route(s)${opts.split ? ', A/B split on' : ''}${opts.displayability ? ', displayability check on' : ''}, sitemap(s) ${Object.keys(files).join(' ')} → .netlify/v1/`,
  );
  return Object.keys(files);
}
